// trường hợp load api saga
export const LIST_NHANVIEN = 'LIST_NHANVIEN';
export const LIST_NHANVIEN_SUCCESS = 'LIST_NHANVIEN_SUCCESS';
export const LIST_NHANVIEN_FAIL = 'LIST_NHANVIEN_FAIL';

export const ADD_NHANVIEN = 'ADD_NHANVIEN';
export const ADD_NHANVIEN_SUCCESS = 'ADD_NHANVIEN_SUCCESS';
export const ADD_NHANVIEN_FAIL = 'ADD_NHANVIEN_FAIL';
